<?php
/**
 * @author:  ccforevercn<1253705861@qq.com>
 * @link     http://ccforever.cn
 * @license  https://github.com/ccforevercn
 * @day:     2020/7/23
 */

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * 菜单默认数据
 * Class MenusTableSeeder
 */
class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => '内容管理',
                'parent_id' => 0,
                'routes' => '',
                'page' => '/message',
                'icon' => 'table',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 100,
            ],
            [
                'id' => 2,
                'name' => '营销管理',
                'parent_id' => 0,
                'routes' => '',
                'page' => '/market',
                'icon' => 'eye',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 80,
            ],
            [
                'id' => 3,
                'name' => 'seo管理',
                'parent_id' => 0,
                'routes' => '',
                'page' => '/seo',
                'icon' => 'eye-open',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 60,
            ],
            [
                'id' => 4,
                'name' => '配置管理',
                'parent_id' => 0,
                'routes' => '',
                'page' => '/config',
                'icon' => 'form',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 40,
            ],
            [
                'id' => 5,
                'name' => '系统管理',
                'parent_id' => 0,
                'routes' => '',
                'page' => '/system',
                'icon' => 'nested',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 20,
            ],
            [
                'id' => 6,
                'name' => '栏目',
                'parent_id' => 1,
                'routes' => '',
                'page' => '/message/columns',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 4,
            ],
            [
                'id' => 7,
                'name' => '信息',
                'parent_id' => 1,
                'routes' => '',
                'page' => '/message/messages',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 3,
            ],
            [
                'id' => 8,
                'name' => '标签',
                'parent_id' => 1,
                'routes' => '',
                'page' => '/message/tags',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 2,
            ],
            [
                'id' => 9,
                'name' => '视图',
                'parent_id' => 1,
                'routes' => '',
                'page' => '/message/views',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 10,
                'name' => '列表',
                'parent_id' => 6,
                'routes' => '/columns/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 11,
                'name' => '总数',
                'parent_id' => 6,
                'routes' => '/columns/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 12,
                'name' => '添加',
                'parent_id' => 6,
                'routes' => '/columns/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 13,
                'name' => '修改',
                'parent_id' => 6,
                'routes' => '/columns/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 14,
                'name' => '删除',
                'parent_id' => 6,
                'routes' => '/columns/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 15,
                'name' => '内容添加/修改/查询',
                'parent_id' => 6,
                'routes' => '/columns/content',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 16,
                'name' => '全部',
                'parent_id' => 6,
                'routes' => '/columns/columns',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 17,
                'name' => '列表',
                'parent_id' => 7,
                'routes' => '/messages/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 18,
                'name' => '总数',
                'parent_id' => 7,
                'routes' => '/messages/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 19,
                'name' => '添加',
                'parent_id' => 7,
                'routes' => '/messages/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 20,
                'name' => '修改',
                'parent_id' => 7,
                'routes' => '/messages/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 21,
                'name' => '删除',
                'parent_id' => 7,
                'routes' => '/messages/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 22,
                'name' => '内容添加/修改/查询',
                'parent_id' => 7,
                'routes' => '/messages/content',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 23,
                'name' => '标签',
                'parent_id' => 7,
                'routes' => '/messages/tags',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 24,
                'name' => '点击量、权重、状态修改',
                'parent_id' => 7,
                'routes' => '/messages/number',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 25,
                'name' => '列表',
                'parent_id' => 8,
                'routes' => '/tags/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 26,
                'name' => '总数',
                'parent_id' => 8,
                'routes' => '/tags/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 27,
                'name' => '添加',
                'parent_id' => 8,
                'routes' => '/tags/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 28,
                'name' => '修改',
                'parent_id' => 8,
                'routes' => '/tags/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 29,
                'name' => '删除',
                'parent_id' => 8,
                'routes' => '/tags/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 30,
                'name' => '标签',
                'parent_id' => 8,
                'routes' => '/tags/tags',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 31,
                'name' => '列表',
                'parent_id' => 9,
                'routes' => '/views/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 32,
                'name' => '总数',
                'parent_id' => 9,
                'routes' => '/views/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 33,
                'name' => '添加',
                'parent_id' => 9,
                'routes' => '/views/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 34,
                'name' => '修改',
                'parent_id' => 9,
                'routes' => '/views/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 35,
                'name' => '删除',
                'parent_id' => 9,
                'routes' => '/views/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 36,
                'name' => '类型',
                'parent_id' => 8,
                'routes' => '/views/views',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 37,
                'name' => '轮播',
                'parent_id' => 2,
                'routes' => '',
                'page' => '/market/banners',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 38,
                'name' => '列表',
                'parent_id' => 37,
                'routes' => '/banners/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 39,
                'name' => '总数',
                'parent_id' => 37,
                'routes' => '/banners/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 40,
                'name' => '添加',
                'parent_id' => 37,
                'routes' => '/banners/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 41,
                'name' => '修改',
                'parent_id' => 37,
                'routes' => '/banners/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 42,
                'name' => '删除',
                'parent_id' => 37,
                'routes' => '/banners/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 43,
                'name' => '友链',
                'parent_id' => 3,
                'routes' => '',
                'page' => '/seo/links',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 44,
                'name' => '缓存',
                'parent_id' => 3,
                'routes' => '',
                'page' => '/seo/caches',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 45,
                'name' => 'Robots',
                'parent_id' => 3,
                'routes' => '',
                'page' => '/seo/robots',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 46,
                'name' => '网站地图',
                'parent_id' => 3,
                'routes' => '',
                'page' => '/seo/sitemap',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 47,
                'name' => '列表',
                'parent_id' => 43,
                'routes' => '/links/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 48,
                'name' => '总数',
                'parent_id' => 43,
                'routes' => '/links/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 49,
                'name' => '添加',
                'parent_id' => 43,
                'routes' => '/links/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 50,
                'name' => '修改',
                'parent_id' => 43,
                'routes' => '/links/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 51,
                'name' => '删除',
                'parent_id' => 43,
                'routes' => '/links/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 52,
                'name' => '首页',
                'parent_id' => 44,
                'routes' => '/cache/index',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 53,
                'name' => '栏目',
                'parent_id' => 44,
                'routes' => '/cache/columns',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 54,
                'name' => '信息',
                'parent_id' => 44,
                'routes' => '/cache/message',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 55,
                'name' => '搜索页',
                'parent_id' => 44,
                'routes' => '/cache/search',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 56,
                'name' => '内容',
                'parent_id' => 45,
                'routes' => '/robots/content',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 57,
                'name' => '修改',
                'parent_id' => 45,
                'routes' => '/robots/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 58,
                'name' => '链接',
                'parent_id' => 46,
                'routes' => '/sitemap/index',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 59,
                'name' => 'html',
                'parent_id' => 46,
                'routes' => '/sitemap/html',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 60,
                'name' => 'xml',
                'parent_id' => 46,
                'routes' => '/sitemap/xml',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 61,
                'name' => 'txt',
                'parent_id' => 46,
                'routes' => '/sitemap/txt',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 62,
                'name' => '分类',
                'parent_id' => 4,
                'routes' => '',
                'page' => '/config/category',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 63,
                'name' => '配置',
                'parent_id' => 4,
                'routes' => '',
                'page' => '/config/message',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 64,
                'name' => '列表',
                'parent_id' => 62,
                'routes' => '/config/category/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 65,
                'name' => '总数',
                'parent_id' => 62,
                'routes' => '/config/category/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 66,
                'name' => '添加',
                'parent_id' => 62,
                'routes' => '/config/category/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 67,
                'name' => '修改',
                'parent_id' => 62,
                'routes' => '/config/category/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 68,
                'name' => '删除',
                'parent_id' => 62,
                'routes' => '/config/category/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 69,
                'name' => '全部',
                'parent_id' => 62,
                'routes' => '/config/category/category',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 70,
                'name' => '列表',
                'parent_id' => 63,
                'routes' => '/config/message/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 71,
                'name' => '总数',
                'parent_id' => 63,
                'routes' => '/config/message/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 72,
                'name' => '添加',
                'parent_id' => 63,
                'routes' => '/config/message/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 73,
                'name' => '修改',
                'parent_id' => 63,
                'routes' => '/config/message/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 74,
                'name' => '删除',
                'parent_id' => 63,
                'routes' => '/config/message/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 75,
                'name' => '管理员',
                'parent_id' => 5,
                'routes' => '',
                'page' => '/system/admins',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 3,
            ],
            [
                'id' => 76,
                'name' => '菜单',
                'parent_id' => 5,
                'routes' => '',
                'page' => '/system/menus',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 2,
            ],
            [
                'id' => 77,
                'name' => '规则',
                'parent_id' => 5,
                'routes' => '',
                'page' => '/system/rules',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 78,
                'name' => '列表',
                'parent_id' => 75,
                'routes' => '/admins/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 3,
            ],
            [
                'id' => 79,
                'name' => '总数',
                'parent_id' => 75,
                'routes' => '/admins/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 3,
            ],
            [
                'id' => 80,
                'name' => '添加',
                'parent_id' => 75,
                'routes' => '/admins/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 81,
                'name' => '修改',
                'parent_id' => 75,
                'routes' => '/admins/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 82,
                'name' => '删除',
                'parent_id' => 75,
                'routes' => '/admins/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 83,
                'name' => '列表',
                'parent_id' => 76,
                'routes' => '/menus/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 2,
            ],
            [
                'id' => 84,
                'name' => '总数',
                'parent_id' => 76,
                'routes' => '/menus/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 2,
            ],
            [
                'id' => 85,
                'name' => '添加',
                'parent_id' => 76,
                'routes' => '/menus/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 86,
                'name' => '修改',
                'parent_id' => 76,
                'routes' => '/menus/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 87,
                'name' => '删除',
                'parent_id' => 76,
                'routes' => '/menus/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 88,
                'name' => '全部',
                'parent_id' => 76,
                'routes' => '/menus/menus',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 89,
                'name' => '列表',
                'parent_id' => 77,
                'routes' => '/rules/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 90,
                'name' => '总数',
                'parent_id' => 77,
                'routes' => '/rules/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 91,
                'name' => '添加',
                'parent_id' => 77,
                'routes' => '/rules/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 92,
                'name' => '修改',
                'parent_id' => 77,
                'routes' => '/rules/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 93,
                'name' => '删除',
                'parent_id' => 77,
                'routes' => '/rules/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 94,
                'name' => '菜单(单个规则)',
                'parent_id' => 77,
                'routes' => '/rules/menu',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 95,
                'name' => '菜单(当前管理员的全部菜单)',
                'parent_id' => 77,
                'routes' => '/rules/menus',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 96,
                'name' => '全部(当前管理员的全部规则)',
                'parent_id' => 77,
                'routes' => '/rules/rules',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 97,
                'name' => '上传管理',
                'parent_id' => 0,
                'routes' => '',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 98,
                'name' => '图片',
                'parent_id' => 97,
                'routes' => '',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 99,
                'name' => '列表',
                'parent_id' => 98,
                'routes' => '/image/list',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 100,
                'name' => '总数',
                'parent_id' => 98,
                'routes' => '/image/count',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 101,
                'name' => '上传',
                'parent_id' => 98,
                'routes' => '/image/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 102,
                'name' => '删除',
                'parent_id' => 98,
                'routes' => '/image/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
        ]);
    }
}
